ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS_DISTRO=melodic

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND noninteractive

MAINTAINER AgentSystem(JSK Lab.) YoheiKakiuchi <youhei@jsk.imi.i.u-tokyo.ac.jp>

RUN apt update -y -q && \
    apt install -q -qq -y apt-utils mesa-utils less x11-xserver-utils x11-utils && \
    apt install -q -qq -y gnupg curl wget lsb-release wmctrl && \
    apt autoremove -y && \
    apt clean -q -y && \
    rm -rf /var/lib/apt/lists/

RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list

## RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | apt-key add -

RUN apt update -y -q && \
    apt install -q -qq -y ros-melodic-desktop-full python-rosdep python-catkin-tools ros-melodic-catkin python-wstool && \
    apt autoremove -y && \
    apt clean -q -y && \
    rm -rf /var/lib/apt/lists/

RUN rosdep init && rosdep update

##
## no entrypoint
##
