ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG CATKIN_WS
ARG CATKIN_BUILD

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND noninteractive

LABEL maintainer="AgentSystem(JSK Lab.) YoheiKakiuchi <youhei@jsk.imi.i.u-tokyo.ac.jp>"

## pip version
#RUN apt update -y -q && \
#    apt install -q -qq -y python-pip && \
#    apt autoremove -y && \
#    apt clean -q -y && \
#    rm -rf /var/lib/apt/lists/ && \
#    pip install urdf2webots

## source version
RUN apt update -y -q && \
    apt install -q -qq -y python-pip && \
    apt autoremove -y && \
    apt clean -q -y && \
    rm -rf /var/lib/apt/lists/

WORKDIR /
RUN git clone --depth=1 https://github.com/agent-system/urdf2webots.git
RUN cd /urdf2webots && pip install -r requirements.txt

### ros API
RUN apt update -y -q && \
    apt install -q -qq -y ros-melodic-webots-ros && \
    apt autoremove -y && \
    apt clean -q -y && \
    rm -rf /var/lib/apt/lists/

### add model_tools
WORKDIR /
RUN if [ "${CATKIN_WS}" = "" ]; then mkdir /catkin_ws; cd /catkin_ws; wstool init src; else cd ${CATKIN_WS}; fi && \
    wstool set -y -t src jsk_model_tools https://github.com/YoheiKakiuchi/jsk_model_tools.git --git --version=parse_urdf_sensor && \
    wstool update -t src jsk_model_tools && \
    source /opt/ros/${ROS_DISTRO}/setup.bash && \
    apt update -q -qq && \
    rosdep update -q -y && \
    rosdep install -q -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error' && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    source /opt/ros/${ROS_DISTRO}/setup.bash && \
    catkin clean -y && \
    catkin config --install && \
    catkin build euscollada ${CATKIN_BUILD} && \
    catkin clean -l -b -d -y
