ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y -q && \
    apt install -q -qq -y python-pip && \
    apt autoremove -y && \
    apt clean -q -y && \
    rm -rf /var/lib/apt/lists/

RUN pip install urdf2webots

RUN apt update -y -q && \
    apt install -q -qq -y ros-melodic-webots-ros && \
    apt autoremove -y && \
    apt clean -q -y && \
    rm -rf /var/lib/apt/lists/

### add model_tools
WORKDIR /
RUN mkdir /catkin_ws; cd /catkin_ws && \
    wstool init src && \
    wstool set -y -t src jsk_model_tools https://github.com/YoheiKakiuchi/jsk_model_tools.git --git --version=parse_urdf_sensor && \
    wstool update -t src && \
    apt update -q -qq && \
    rosdep update -q -y && \
    rosdep install -q -y -r --from-paths src --ignore-src || echo 'Ignore rosdep error' && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    source /opt/ros/${ROS_DISTRO}/setup.bash && \
    catkin config --install && \
    catkin build euscollada && \
    catkin clean -l -b -d -y
